/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6UsCReE1oWY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'
import { Chivo } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";

export function elearningSplash() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="bg-gradient-to-r from-primary to-primary-foreground py-20 md:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 md:grid-cols-2 md:items-center">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold text-background md:text-5xl">
                Unlock Your Potential with Our E-Learning Platform
              </h1>
              <p className="text-background/80 md:text-lg">
                Explore a vast library of courses, learn from industry experts, and achieve your learning goals.
              </p>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-background px-6 text-sm font-medium text-primary shadow-sm transition-colors hover:bg-background/90 focus:outline-none focus:ring-2 focus:ring-background focus:ring-offset-2"
                prefetch={false}
              >
                Get Started
              </Link>
            </div>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Hero Image"
              className="mx-auto rounded-lg shadow-lg"
            />
          </div>
        </div>
      </section>
      <section className="py-16 md:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-8 md:grid-cols-3">
            <div className="space-y-2">
              <CompassIcon className="h-8 w-8 text-primary" />
              <h3 className="text-xl font-semibold">Explore Courses</h3>
              <p className="text-muted-foreground">
                Browse our extensive library of courses across a wide range of subjects and skill levels.
              </p>
            </div>
            <div className="space-y-2">
              <ClapperboardIcon className="h-8 w-8 text-primary" />
              <h3 className="text-xl font-semibold">Learn from Experts</h3>
              <p className="text-muted-foreground">
                Learn from industry-leading instructors who are passionate about sharing their knowledge.
              </p>
            </div>
            <div className="space-y-2">
              <BadgeIcon className="h-8 w-8 text-primary" />
              <h3 className="text-xl font-semibold">Earn Certificates</h3>
              <p className="text-muted-foreground">
                Complete courses and earn certificates to showcase your skills and achievements.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-muted py-16 md:py-24">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold md:text-4xl">Explore Our Most Popular Courses</h2>
            <p className="text-muted-foreground md:text-lg">
              Discover the courses that have captured the attention of our learners.
            </p>
          </div>
          <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            <Card>
              <CardContent className="space-y-2">
                <img src="/placeholder.svg" width={300} height={200} alt="Course Thumbnail" className="rounded-t-md" />
                <h3 className="text-xl font-semibold">Introduction to Web Development</h3>
                <p className="text-muted-foreground">
                  Learn the fundamentals of web development, including HTML, CSS, and JavaScript.
                </p>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-1 text-sm text-muted-foreground">
                    <ClockIcon className="h-4 w-4" />
                    <span>12 hours</span>
                  </div>
                  <Link
                    href="#"
                    className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Enroll
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="space-y-2">
                <img src="/placeholder.svg" width={300} height={200} alt="Course Thumbnail" className="rounded-t-md" />
                <h3 className="text-xl font-semibold">Data Science Fundamentals</h3>
                <p className="text-muted-foreground">
                  Dive into the world of data science and learn essential skills for data analysis and visualization.
                </p>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-1 text-sm text-muted-foreground">
                    <ClockIcon className="h-4 w-4" />
                    <span>20 hours</span>
                  </div>
                  <Link
                    href="#"
                    className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Enroll
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="space-y-2">
                <img src="/placeholder.svg" width={300} height={200} alt="Course Thumbnail" className="rounded-t-md" />
                <h3 className="text-xl font-semibold">Mastering Digital Marketing</h3>
                <p className="text-muted-foreground">
                  Learn the essential strategies and techniques for effective digital marketing campaigns.
                </p>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-1 text-sm text-muted-foreground">
                    <ClockIcon className="h-4 w-4" />
                    <span>18 hours</span>
                  </div>
                  <Link
                    href="#"
                    className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Enroll
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  );
}

interface IconProps {
  className?: string;
}

function BadgeIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
    </svg>
  );
}

function ClapperboardIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.2 6 3 11l-.9-2.4c-.3-1.1.3-2.2 1.3-2.5l13.5-4c1.1-.3 2.2.3 2.5 1.3Z" />
      <path d="m6.2 5.3 3.1 3.9" />
      <path d="m12.4 3.4 3.1 4" />
      <path d="M3 11h18v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" />
    </svg>
  );
}

function ClockIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function CompassIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  );
}

function XIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}