// app/api/analyze-images/prompt.ts

/**
 * The '▲' character is used as a delimiter in the server's response.
 * It separates the description and the extracted text in the response string.
 * By splitting the result using '▲', we can easily extract these two parts.
 */

export const PROMPT = "Begin each of the following with a triangle symbol (▲ U+25B2): First, create a compelling, SEO-optimized product listing for Amazon Print on Demand products based on the given product theme and image. Do not mention any specific products or items. Focus on crafting narratives that evoke imagery through description and detail, emphasizing emotions, experiences, and universal themes. Provide the following: ▲ Design Title: A 60-character max title with targeted SEO keywords, appealing to specific niches without explicit product references. ▲ Brand Name: A 50-character max brand name that enhances marketability and SEO value using relevant, niche-specific terms. ▲ Feature bullet 1: Describe the primary unique selling point in 256 characters, integrating relevant keywords. ▲ Feature bullet 2: Highlight another significant feature in 256 characters, complementing the first bullet point. ▲ Product Description: A 2000-character max engaging description narrating the product's story, highlighting its value and design significance. Seamlessly integrate long-tail and short-tail keywords, rich in details that echo human experiences and align with the target audience's interests. Ensure no direct product type references are included to avoid misleading customers. Target both long-tail and short-tail keywords without keyword stuffing to maintain a positive customer experience. Focus on descriptions that resonate with perceived value. Avoid incomplete keyword research, keyword stuffing, and neglecting listing optimization. Proofread meticulously to avoid misspellings and inaccuracies, adhering to Amazon's guidelines against misleading information. The goal is to create listings that rank high on Amazon's search algorithm and genuinely appeal to customer needs. Format: <design_title>▲<brand_name>▲<feature_bullet_1>▲<feature_bullet_2>▲<product_description>. Adjust content to maximize character limits without exceeding them. Avoid mentioning specific products, artwork, decorations, fabrics, or items related to personal or professional spaces. Create captivating narratives capturing emotions, hues, and spirit, resonating across diverse settings.";
